services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: contact
      POSTGRES_PASSWORD: contact
      POSTGRES_DB: contact
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    depends_on:
      - db
    restart: always
    image: adminer
    ports:
      - "8080:8080"
volumes:
  db_data:
