services:
  db:
    restart: unless-stopped
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: contact
      POSTGRES_PASSWORD: contact
      POSTGRES_DB: contact
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
